import logging
from odoo.upgrade import util

_logger = logging.getLogger(__name__)


def migrate(cr, version):
    util.records.remove_record(cr, "rrhh.act_rrhh_prestamo")
    util.records.remove_record(cr, "rrhh.act_rrhh_prestamo_2")
    util.records.remove_record(cr, "rrhh.action_rrhh_prestamo")
    util.records.remove_record(cr, "rrhh.action_planilla")
    util.records.remove_record(cr, "rrhh.action_recibo")
    util.records.remove_record(cr, "rrhh.rrhh_menu_prestamo")
    util.records.remove_record(cr, "rrhh.menu_planilla")
    util.records.remove_record(cr, "rrhh.menu_recibo")
    util.records.remove_record(cr, "rrhh.rrhh_recibo")
    util.records.remove_record(cr, "rrhh.action_planilla")
    util.records.remove_record(cr, "rrhh.action_planilla_wizard")
    util.records.remove_record(cr, "rrhh.action_igss_wizard")
    util.records.remove_record(cr, "rrhh.action_rrhh_informe_empleador")
    util.records.remove_record(cr, "rrhh.action_libro_salarios")
    util.records.remove_record(cr, "rrhh.action_rrhh_libro_salarios")
    util.records.remove_record(cr, "rrhh.action_planilla")
    util.records.remove_record(cr, "rrhh.action_planilla_wizard")
    util.records.remove_record(cr, "rrhh.HrSalaryRule_08")
    util.records.remove_record(cr, "rrhh.HrSalaryRule_13")

    util.records.remove_view(cr, xml_id="rrhh.rrhh_view_employee_prestamo_form")
    util.records.remove_view(cr, xml_id="rrhh.rrhh_view_employee_prestamo_linea_form")
    util.records.remove_view(cr, xml_id="rrhh.rrhh_edit_holiday_status_form")
    util.records.remove_view(cr, xml_id="rrhh.rrhh_view_hr_payslip_form")
    util.records.remove_view(cr, xml_id="rrhh.rrhh_hr_work_entry_type_view_form")
    util.records.remove_view(cr, xml_id="rrhh.libro_salarios")
    util.records.remove_view(cr, xml_id="rrhh.recibo")
    util.records.remove_view(cr, xml_id="rrhh.libro_salarios")
    util.records.remove_view(cr, xml_id="rrhh.view_planilla_list")
    util.records.remove_view(cr, xml_id="rrhh.view_planilla_form")
    util.records.remove_view(cr, xml_id="rrhh.view_planilla_columna_form")
    util.records.remove_view(cr, xml_id="rrhh.view_recibo_list")
    util.records.remove_view(cr, xml_id="rrhh.view_recibo_form")
    util.records.remove_view(cr, xml_id="rrhh.view_recibo_linea_form")
    util.records.remove_view(cr, xml_id="rrhh.planilla_pdf")
    util.records.remove_view(cr, xml_id="rrhh.view_planilla_wizard_form")
    util.records.remove_view(cr, xml_id="rrhh.view_igss_wizard_form")
    util.records.remove_view(cr, xml_id="rrhh.view_rrhh_informe_empleador")
    util.records.remove_view(cr, xml_id="rrhh.view_rrhh_libro_salarios")
    util.records.remove_view(cr, xml_id="rrhh.view_planilla_wizard_form")

    util.records.rename_xmlid(cr, "rrhh.salario_promedio_entrada", "rrhh.entrada_salario_promedio")
    util.records.rename_xmlid(cr, "rrhh.dias_trabajados_entrada", "rrhh.entrada_dias_trabajados")
    util.records.rename_xmlid(cr, "rrhh.dias_calendario_entrada", "rrhh.entrada_dias_calendario")
    util.records.rename_xmlid(cr, "rrhh.HrSalaryRule_01", "rrhh.regla_sueldo_base")
    util.records.rename_xmlid(cr, "rrhh.HrSalaryRule_02", "rrhh.regla_bonificacion_incentivo")
    util.records.rename_xmlid(cr, "rrhh.HrSalaryRule_03", "rrhh.regla_bono_14")
    util.records.rename_xmlid(cr, "rrhh.HrSalaryRule_04", "rrhh.regla_aguinaldo")
    util.records.rename_xmlid(cr, "rrhh.HrSalaryRule_05", "rrhh.regla_vacaciones")
    util.records.rename_xmlid(cr, "rrhh.HrSalaryRule_06", "rrhh.regla_indemnizacion")
    util.records.rename_xmlid(cr, "rrhh.HrSalaryRule_07", "rrhh.regla_descuentos_varios")
    util.records.rename_xmlid(cr, "rrhh.HrSalaryRule_10", "rrhh.regla_igss_laboral")
    util.records.rename_xmlid(cr, "rrhh.HrSalaryRule_11", "rrhh.regla_igss_patronal")
    _logger.info("Borrar vistas viejas")
