from . import hr_employee
from . import hr_version
from . import hr_payslip
from . import res_company
from . import account_payment
from . import hr_work_entry
from . import hr_leave_type
from . import rrhh_prestamo
from . import rrhh_historial_salario
from . import rrhh_planilla
from . import rrhh_recibo